name: nmea_plugin
description: A Flutter plugin to listen for and parse native NMEA messages from Android's GPS hardware. Provides a simple stream of structured NMEA data like GGA, GSA, and GSV.
version: 0.0.1
homepage: https://github.com/leijingxing/nmea_plugin.git
repository: https://github.com/leijingxing/nmea_plugin.git

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hyzh.nmea_plugin
        pluginClass: NmeaPlugin
      ios:
        pluginClass: NmeaPlugin
